site_name: Project60 Membership Extension
repo_url: https://github.com/Project60/org.project60.membership
site_description: 'A guide for the membership extension.'
site_author: 'systopia'
theme:
  name: material

nav:
  - 'Introduction': index.md
  - 'Configuration': configuration.md
  - 'Automation': automation.md
  - 'How To Guide': how-to-guide.md


markdown_extensions:
  - attr_list
  - admonition
  - def_list
  - codehilite
  - toc:
      permalink: True
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.tilde
  - pymdownx.betterem
  - pymdownx.mark

plugins:
  - search:
      lang: en
